version: '3.2'
services:
  emqx:
    image: emqx/emqx:4.4.3
    container_name: mqtt_emqx
    # restart: always
    ports:
      - 1883:1883
      - 8081:8081
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    volumes:
      - ./acl.conf:/opt/emqx/etc/acl.conf
      # - ./emqx.conf:/opt/emqx/etc/emqx.conf
      # - ./ssl_dist.conf:/opt/emqx/etc/ssl_dist.conf
      - ./data:/opt/emqx/data
      # - ./cert/server.key:/etc/certs/key.pem
      # - ./cert/server.pem:/etc/certs/cert.pem
      # - ./cert/ca.pem:/etc/certs/cacert.pem
    
# kill -HUP 1
#  默认账号：admin 密码：public
# docker run -d --name emqx -p 1883:1883 -p 8083:8083 -p 8883:8883 -p 8084:8084 -p 18083:18083 emqx/emqx:4.4.3