version: '3'
services:
  redis:
    image: nginx:1.21.6
    container_name: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
    ports:
      - 80:80
