version: '3'
services:
  mysql57:
    image: mysql/mysql-server:5.7.37
    container_name: mysql57
    restart: always
    volumes:
      - ./57/data:/var/lib/mysql
      - ./57/my.cnf:/etc/my.cnf
      - ./57/agm:/agm # 智慧食堂项目脚本
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "root"
    # 将my.cnf权限设置为644,否则windows下配置文件不生效:[Warning] World-writable config file '.cnf' is is ignored
    command: >
          bash -c "
          chmod 644 /etc/my.cnf
          && /entrypoint.sh mysqld
          "
  # mysql572:
  #   image: mysql/mysql-server:5.7.37
  #   container_name: mysql572
  #   volumes:
  #     - ./572/data:/var/lib/mysql
  #     - ./572/my.cnf:/etc/my.cnf
  #   ports:
  #     - 3308:3306
  #   environment:
  #     MYSQL_ROOT_HOST: "%"
  #     MYSQL_ROOT_PASSWORD: "root"