version: '3'
services:
  openresty:
    image: openresty/openresty:1.19.9.1-5-alpine
    container_name: openresty
    # restart: always
    volumes:
      - ./conf.d/:/etc/nginx/conf.d
      - ./logs:/usr/local/openresty/nginx/logs
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    ports:
      - 8080:80
