version: '3.2'
services:
  zookeeper:
    image: zookeeper:3.8.0
    container_name: kafka_zk
    ports:
      - 2181:2181
    # volumes:
    #   - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.1.1
    container_name: kafka
    ports:
      - 9092:9092
      - 9988:9988
    volumes:
      - ./kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - JMX_PORT=9988
      - KAFKA_JMX_OPTS= -Djava.rmi.server.hostname=192.168.11.1 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false
    depends_on:
      - zookeeper


# gui:
  # EFAK
  # https://juejin.cn/post/7069409626223018015